### PR TITLE
Update Test Suites comments.

### PR DESCRIPTION
**Pull request by chenlu0616**

### CODE REVIEW

**Comment by yazeng** [comment]
Can one of the admins verify this patch?

**Comment by yazeng** [comment]
Can one of the admins verify this patch?

**Comment by yazeng** [comment]
Can one of the admins verify this patch?

**Comment by yazeng** [comment]
Can one of the admins verify this patch?

**Comment by yazeng** [comment]
Can one of the admins verify this patch?

**Comment by yazeng** [comment]
Can one of the admins verify this patch?

**Comment by JiajunW** [comment]
I will take care of this PR later today.

**Pull request merged**
