### PR TITLE
Refactor cert creation

### PR DESCRIPTION
**Pull request by borgee**
The powershell cert management cmdlets are suitable for this task. This results shorter, and more readable script.

### CODE REVIEW

**Comment by yazeng** [comment]
Can one of the admins verify this patch?

**Comment by yazeng** [comment]
Can one of the admins verify this patch?

**Comment by yazeng** [comment]
Can one of the admins verify this patch?

**Comment by yazeng** [comment]
Can one of the admins verify this patch?

**Comment by yazeng** [comment]
Can one of the admins verify this patch?

**Comment by yazeng** [comment]
Can one of the admins verify this patch?

**Comment by yazeng** [comment]
Can one of the admins verify this patch?

**Comment by borgee** [comment]
I have signed the CLA.

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by yazeng** [comment]
add to whitelist

**Comment by yazeng** [comment]
RDP

**Comment by yazeng** [comment]
RDP

**Comment by yazeng** [comment]
RDP

**Comment by yazeng** [comment]
RDP

**Comment by yazeng** [comment]
RDP

**Comment by yazeng** [comment]
Hi Kristóf, 
Your contribution is highly appreciated. 
Thank you very much!

BRs,
Yan

**Pull request merged**
