### PR TITLE
Fix typo in a testcase name

### PR DESCRIPTION
**Pull request by ligurio**

### CODE REVIEW

**Comment by WinProtoTest** [comment]
Thanks for the pull request. We'll review it as soon as possible.

**Comment by yazeng** [comment]
Hi Sergey,

  Good catch and thanks for the pr. Could you please help modify the test design spec too? In this case, it is MS-RDPBCGR_ClientTestDesignSpecification.md under this folder: https://github.com/microsoft/WindowsProtocolTestSuites/tree/staging/TestSuites/RDP/Client/docs
The line 1192 should be modified.

Thank you again!
Yan

**Comment by ligurio** [comment]
@yazeng Sure! Done.

**Comment by yazeng** [comment]
Thank you!

**Pull request merged**
