### PR TITLE
Add Kerberos Plugin

### PR DESCRIPTION
**Pull request by Buffest**
Added Kerberos plugin and fixed hyper link bugs in Kerberos/UserGuide.md

### CODE REVIEW

**Comment by Buffest** [comment]
Kerberos

**Comment by JiajunW** [comment]
I will merge this PR together with #79 later today.

**Comment by Buffest** [comment]
Kerberos

**Comment by yazeng** [comment]
Approved

**Comment by Buffest** [comment]
PTM

**Pull request closed without merging**
